//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWarden.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogId { get; set; }
        public string MachineName { get; set; }
        public System.DateTime Logged { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserFirstName { get { return (Users == null) ? (null) : (Users.FirstName); } }
        public string UserSecondName { get { return (Users == null) ? (null) : (Users.SecondName); } }
        public string UserThirdName { get { return (Users == null) ? (null) : (Users.ThirdName); } }
        public string UserDivisionName { get { return (Users == null) ? (null) : (Users.Division.Name); } }
        public string UserIsVerify { get { return (Users == null) ? (null) : ((Users.IsVerify) ? ("Верифицирован") : ("Не верифицирован")); } }

        [JsonIgnore]
        public virtual Users Users { get; set; }
    }
}
