//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWarden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEnterAct
    {
        public int ProductEnterActId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime EnterDate { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public bool HighPriotity { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Users Users { get; set; }
    }
}
