//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWarden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedUserMessages
    {
        public int BlockedUserMessageId { get; set; }
        public int SendlerUserId { get; set; }
        public Nullable<int> DestinationUserId { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
