//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWarden.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.BlockedUserMessages = new HashSet<BlockedUserMessages>();
            this.BlockedUserMessages1 = new HashSet<BlockedUserMessages>();
            this.Logs = new HashSet<Logs>();
            this.Order = new HashSet<Order>();
            this.ProductEnterAct = new HashSet<ProductEnterAct>();
        }

        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        [DefaultValue(null)]
        public string ThirdName { get; set; }
        [DefaultValue(null)]
        public string Login { get; set; }
        [DefaultValue(null)]
        public string Password { get; set; }
        [DefaultValue(null)]
        public string SecretWord { get; set; }
        public int DivisionId { get; set; }
        public Nullable<int> PermissionId { get; set; }
        [DefaultValue(false)]
        public bool IsBlocked { get; set; }
        public bool Gender { get; set; }
        [DefaultValue(false)]
        public bool IsVerify { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockedUserMessages> BlockedUserMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockedUserMessages> BlockedUserMessages1 { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Permission Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEnterAct> ProductEnterAct { get; set; }
    }
}
